FROM golang:latest

RUN mkdir /app
ADD . /app
WORKDIR /app

RUN go get -u github.com/gorilla/mux
RUN go get -u gorm.io/driver/mysql
RUN go get -u gorm.io/gorm

RUN go build -o main .

EXPOSE 8080

CMD ["/app/main"]